#!/bin/bash

set -e

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

require_configured release
deps_env
cd "$SCRIPT_DIR/release"

build_target parser 1
build_target colin
build_target colin-clp
if has_target release colin-cplex; then
    build_target colin-cplex
fi
