#!/bin/bash

set -e

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

require_configured static
cd "$SCRIPT_DIR/static"

build_target parser 1
build_target colin
build_target colin-clp
if has_target static colin-cplex; then
    build_target colin-cplex
fi
