#!/bin/bash

set -e

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

require_configured debug
cd "$SCRIPT_DIR/debug"

build_target parser 1
build_target colin
build_target colin-clp
if has_target debug colin-cplex; then
    build_target colin-cplex
fi
